import type { Token, ExplorationResult } from "./ExplorationResult";

export const mockAnalysis: Token[] = [
    { text: "Senior", weight: 1.0, is_word: true },
    { text: " ", weight: 0.0, is_word: false },
    { text: "Python", weight: 0.87, is_word: true },
    { text: " ", weight: 0.0, is_word: false },
    { text: "Backend", weight: 0.72, is_word: true },
    { text: " ", weight: 0.0, is_word: false },
    { text: "Developer", weight: 0.65, is_word: true },
    { text: ".", weight: 0.0, is_word: false },
    { text: " ", weight: 0.0, is_word: false },
    { text: "Опыт", weight: 0.15, is_word: true },
    { text: ":", weight: 0.0, is_word: false },
    { text: " ", weight: 0.0, is_word: false },
    { text: "5", weight: 0.08, is_word: true },
    { text: " ", weight: 0.0, is_word: false },
    { text: "лет", weight: 0.05, is_word: true },
    { text: ".", weight: 0.0, is_word: false },
    { text: " ", weight: 0.0, is_word: false },
    { text: "Навыки", weight: 0.12, is_word: true },
    { text: ":", weight: 0.0, is_word: false },
    { text: " ", weight: 0.0, is_word: false },
    { text: "Python", weight: 0.82, is_word: true },
    { text: ",", weight: 0.0, is_word: false },
    { text: " ", weight: 0.0, is_word: false },
    { text: "FastAPI", weight: 0.45, is_word: true },
    { text: ",", weight: 0.0, is_word: false },
    { text: " ", weight: 0.0, is_word: false },
    { text: "PostgreSQL", weight: 0.38, is_word: true },
    { text: ",", weight: 0.0, is_word: false },
    { text: " ", weight: 0.0, is_word: false },
    { text: "Docker", weight: 0.32, is_word: true },
    { text: ",", weight: 0.0, is_word: false },
    { text: " ", weight: 0.0, is_word: false },
    { text: "Kafka", weight: 0.28, is_word: true },
    { text: ".", weight: 0.0, is_word: false },
    { text: " ", weight: 0.0, is_word: false },
    { text: "Образование", weight: 0.1, is_word: true },
    { text: ":", weight: 0.0, is_word: false },
    { text: " ", weight: 0.0, is_word: false },
    { text: "МГУ", weight: 0.18, is_word: true },
    { text: ",", weight: 0.0, is_word: false },
    { text: " ", weight: 0.0, is_word: false },
    { text: "2020", weight: 0.05, is_word: true },
    { text: ".", weight: 0.0, is_word: false },
];

export const mockExplorationResult: ExplorationResult = {
    resume_id: 99999,
    tokens: mockAnalysis,
    status: "success",
};
